apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: omniwatch
  labels:
    app: order-service
    tier: backend
    phase: "1"
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
