apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: omniwatch
  labels:
    app: order-service
    tier: backend
    phase: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        tier: backend
        phase: "1"
    spec:
      containers:
        - name: order-service
          image: gcr.io/omniwatch/order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
              name: http
              protocol: TCP
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otelcol:4317
          envFrom:
            - configMapRef:
                name: order-service-config
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
