apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: omniwatch
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: omniwatch
data:
  CLICKHOUSE_HOST: clickhouse
  CLICKHOUSE_PORT: "8123"
  CLICKHOUSE_DB: omniwatch
  CLICKHOUSE_USER: default
  CLICKHOUSE_PASSWORD: ""
