apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: omniwatch
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: omniwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
            - --address
            - ":9010"
            - --console-address
            - ":9001"
          ports:
            - containerPort: 9001
              name: console
            - containerPort: 9010
              name: api
          env:
            - name: MINIO_ROOT_USER
              value: minioadmin
            - name: MINIO_ROOT_PASSWORD
              value: minioadmin
          startupProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: omniwatch
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: omniwatch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
