apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: omniwatch
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: omniwatch
spec:
  ports:
    - port: 9001
      targetPort: 9001
      name: console
    - port: 9010
      targetPort: 9010
      name: api
  selector:
    app.kubernetes.io/name: minio
